{
 "title": "Main",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Transactions per method",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_data_repository_invocations_seconds_count{exception=\"None\",state=\"SUCCESS\",} ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Transactions ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/categoria\",}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/categoria/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"aplicacaologs\"} |~ \"(Erro foi)\" [1m])"
    }
   ]
  },
  {
   "title": "JVM usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{job=\"aplicacaologs\"}  |~ \"WARN|ERROR\""
    }
   ]
  },
  {
   "title": "Containers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"docker\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}