server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
- job_name: aplicacao
  static_configs:
  - targets:
      - localhost
    labels:
      job: aplicacaologs
      __path__: /Users/raphael.ferreira/Documents/Projeto_dev/JavaApi/gestao-vendas/application.log