{
 "title": "Teste",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Transactions ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/categoria\",}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/categoria/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"docker\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"aplicacaologs\"} |~ \"(Erro foi)\" [1m])"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{job=\"aplicacaologs\"}  |~ \"WARN|ERROR\""
    }
   ]
  }
 ]
}